### ISSUE TITLE
Sorry... how to install/run? 

### ISSUE THREAD

**Issue by TomWhitwell** [rsimmons/isovoxel#1]
Hi, would really like to get this running, but don't have much experience of javascript outside browsers. Could you do a couple of lines on getting started? 
Thanks!

**Comment by rsimmons** [comment]
Hi Tom! I'm a huge fan of your work, and as I write this I'm admiring a Mutable Ears and Radio Music on my desk :)

I had just been thinking recently that I should revisit this code and clean it up. It would help me to know, are you interested in pen plotting, or laser cutting the results, or some other SVG export or just seeing it on a screen?

**Comment by TomWhitwell** [comment]
Hi, that's great to hear!  I have an Axidraw on the way, so I'd be looking for SVG or some other interface there.

**Comment by rsimmons** [comment]
OK, I've added some documentation to the bottom of the main README. I don't actually (yet) have a pen plotter myself, so I haven't tested the full end to end process, but the SVG output *should* be optimized for a plotter in that the lines are sorted to be drawn in an alternating back and forth motion. Let me know if you have any issues, or any success with plotting!

**Comment by TomWhitwell** [comment]
Fantastic, thank you, it's working! Will share some plots once I get a machine .

**Comment by TomWhitwell** [comment]
https://user-images.githubusercontent.com/1890544/107127082-985f2280-68ab-11eb-9046-4738652844df.mov

Email me tom@musicthing.co.uk and I'll send you a print

**Comment by rsimmons** [comment]
Excellent! Will do, thanks so much.
